# Site settings
course_name: System Analysis and Design
course_description: "Just as solving a mathematical problem requires identifying its complexities and designing appropriate strategies before arriving at a solution, developing computer systems for a diverse user base demands thorough analysis and design. In this course, students will learn essential skills in requirements analysis, feasibility analysis, modeling, process analysis, architecture design, and UI/UX design. Additionally, the course covers planning and management skills necessary for software development, including methodologies, process automation, and project management concepts."
course_semester: "Fall 2024"

baseurl: "/sad" # the subpath of your site, e.g. /blog/
url: "http://sut-ce-courses.github.io/" # the base hostname & protocol for your site

schoolname: "Sharif University of Technology"
schoolurl: "https://sharif.edu"
twitter_username: maar1395

address: |
    Computer Engineering Department
    Sharif University of Technology
    Tehran

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
